import { Navigation, Settings } from "@/components";
import { Dialog } from "@/components/ui/dialog";
import { Sheet } from "@/components/ui/sheet";
import type { Metadata } from "next";
import { pixel } from "./fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Strategem Hero",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={pixel.className}>
        <Sheet>
          <Dialog>
            <Navigation />
            {children}
            <Settings />
          </Dialog>
        </Sheet>
      </body>
    </html>
  );
}
