import type { Metadata } from "next";
import "./globals.css";
import { pixel } from "./fonts";

export const metadata: Metadata = {
  title: "Strategem Hero",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={pixel.className}>{children}</body>
    </html>
  );
}
